name = "mlabs-haskell/bet-ref-aiken"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'mlabs-haskell/bet-ref-aiken'"

[repository]
user = "mlabs-haskell"
project = "bet-ref-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
